server:
  port: 8081

spring:
  application:
    name: friendship

  datasource:
    url: jdbc:postgresql://localhost:5433/myfriendship
    username: myfriend
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  jwt:
    issuer: user-service
    access-token-ttl: 15m
    secret: secret
